prompts = [
    "After a long day of work, you sit down to watch some TV, but it shuts off on its own.You turn it back on, "
    "but it turns off again.",
    "You hear a large clap outside. You get up to look…",
    "A small puppy steps out of the shadows.",
    "You look in the mirror, but it isn’t you looking back!",
    "Imagine your life in ten years.",
    "The carnival comes to town, but everything is not as it seems.",
    "You hear the waves crashing on the beach",
    "That feeling in the pit or your stomach.",
    "I'll never get that image out of my head.",
    "Her favorite color was purple.",
    "He loved her...",
    "She couldn't tell him. He would never forgive her.",
    "Just like that, things would never be the same.",
    "It was a comfortable life.",
    "Mums the word. You can't tell anyone. Ever!",
    "It started out like any other night.",
    "The last time I flew I was only eight years old.",
    "She loved him...",
    "Wait until you hear the worst part.",
    "It's a tale like no other.",
    "It was a beautiful Spring morning.",
    "Write about someone risking their life for...",
    "We've been compromised. A double agent is among us.",
    "That was the last time we ever heard from him/her.",
    "There is a monster under your bed.",
    "You survived by a miracle. Now you're alone on a deserted Island. At least that's what you thought.",
    "You could almost see it, like a wrinkle in the fabric of time.",
    "You prepared your entire life for this one moment. Don't mess it up.",
    "The silence was deafening.",
    "A graveyard is supposed to be a spooky place. Yet here I am, with a sense of calm that even I don't understand.",
    "You open a time capsule, but the items are cursed.",
    "Your life is a tv show.",
    "You awake from cryo-sleep. This world is not the world you once knew.",
    "You awake from a ten year coma.",
    "You find yourself in a world where humans are another creature's pet.",
    "You are a spy tasked with an impossible mission.",
    "You find a secret room in your home.",
    "You explore an abandoned town and discover why no one will ever return.",
    "Write about yourself.",
    "You find a note you were never meant to see.",
    "As you go through your grandfather's belongings, you come across a locked chest. You force it open and find "
    "folders marked \"TOP SECRET\". You begin looking through them and can't believe your eyes."
]